version: '3.1'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
  wordpress:
    depends_on:
      - mysql
    image: wordpress
    volumes:
      - ./wp_data:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_PASSWORD: example
